### ISSUE TITLE
Error: Mnemonic invalid or undefined

### ISSUE THREAD

**Issue by ceodaniyal** [vedant080102/Polling-System-using-Blockchain#1]
Hello Bro,

I was trying to run this project on my computer,
I have installed all the required node modules in the main folder as well as in the frontend folder,
but I keep getting this error 

"Error: Mnemonic invalid or undefined
    at C:\Users\kdani\Desktop\codes\Polling-System-using-Blockchain\node_modules\truffle-hdwallet-provider\dist\webpack:\truffle-hdwallet-provider\src\index.js:60:1
    at new checkBIP39Mnemonic (C:\Users\kdani\Desktop\codes\Polling-System-using-Blockchain\node_modules\truffle-hdwallet-provider\dist\webpack:\truffle-hdwallet-provider\src\index.js:90:1)
    at Object.<anonymous> (C:\Users\kdani\Desktop\codes\Polling-System-using-Blockchain\test\Poll.test.js:9:18)
    at Module._compile (node:internal/modules/cjs/loader:1378:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1437:10)
    at Module.load (node:internal/modules/cjs/loader:1212:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1028:12)
    at cjsLoader (node:internal/modules/esm/translators:359:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:308:7)
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at ModuleLoader.import (node:internal/modules/esm/loader:323:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:430:15)
    at formattedImport (C:\Users\kdani\AppData\Roaming\npm\node_modules\mocha\lib\nodejs\esm-utils.js:9:14)
    at Object.exports.requireOrImport (C:\Users\kdani\AppData\Roaming\npm\node_modules\mocha\lib\nodejs\esm-utils.js:42:28)      
    at Object.exports.loadFilesAsync (C:\Users\kdani\AppData\Roaming\npm\node_modules\mocha\lib\nodejs\esm-utils.js:100:20)      
    at singleRun (C:\Users\kdani\AppData\Roaming\npm\node_modules\mocha\lib\cli\run-helpers.js:125:3)
    at Object.exports.handler (C:\Users\kdani\AppData\Roaming\npm\node_modules\mocha\lib\cli\run.js:370:5)"

Frontend is running fine but I can't run the main file, do I need to compile that compile.js file? 
Help me in whichever way possible bro.

**Comment by vedant080102** [comment]
your env must look this (in the root folder): 

secret_key=
apikey=https://goerli.infura.io/v*/***apikey
address=http://127.0.0.1:7546
nmeumo=

---
Give me some time and i will get back to you with the proper flow
